analytics.account={"id"\:1647931,"name"\:"Tunnel Demo","uuid"\:"dfac34b9-c719-4c63-898a-28530081dda2","domain"\:"tunneldemo"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization="{\\"accountId\\"\:1649991,\\"accountUuid\\"\:\\"4888ed9f-5d74-49a1-a7f1-df1737b20416\\",\\"id\\"\:3288056,\\"name\\"\:\\"Northstar Org\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://northguard.katalon.io/"
analytics.project="{\\n  \\"id\\"\: 3251113,\\n  \\"name\\"\: \\"Northstar PoC\\",\\n  \\"teamId\\"\: 3222987,\\n  \\"organizationId\\"\: 3288056,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3222987\\n}"
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email="kevin.jackey@katalon.com"
onpremise.password="dmai17WplE+wnhFc21HshYOJzJowldbjBl4S7Hwy0BtcS7ZmeKwPgg\=\="
